// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srxwgoximioevyadffwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyeHdnb3hpbWlvZXZ5YWRmZndiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTA0MDMsImV4cCI6MjA2MzgyNjQwM30.kaJH8wkisM5b34rNHl5XUkj6l5WrWiOCWDu-Qiq96RA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);